---

- name: "Checking system OS"
  fail:
    msg: "This is not a Debian based distribution. Proxmox VE is not compatible"
  when: ansible_distribution != "Debian"

- include: install-packages.yml

- include: config-network.yml

- include: config-storage-lvm.yml
  when: "{{ proxmox_ve__storage_lvm | length }} > 0"
