---
# handlers file for proxmox-ve

- name: Reboot Host
  command: echo "Host configuration might have big changes. Highly recommended to reboot the host."

# - name: reload $service
#   sudo: yes
#   service: name=$service state=reloaded
